### ISSUE TITLE
Infusion Stabilizers 

### ISSUE THREAD

**Issue by Fortist** [Modbder/ThaumicBases#10]
Not only does it mark a lot of things as stabilizers, most of them dont actually work according to WItching Gadget's tool to check stability.
I'd also like a config to hide that line of text, to have it be gone altogether, or underneath a "Shift" or "CTRL" button.

**Comment by Modbder** [comment]
It's not TB. I do not know what addon adds the text to the items, but it is certainly not TB.

**Comment by Fortist** [comment]
Ah, I see.
