### ISSUE TITLE
[Suggestion] Research Points generator.

### ISSUE THREAD

**Issue by OneEyeMaker** [Modbder/ThaumicBases#12]
DummyThinking, возможно моё предложение будет совсем не по лору, не по теме, и я совсем не по адресу обращаюсь... И всё же, появилась у меня идея, которую можно бы добавить в этот чудный аддон.
Моё предложение касается генерации очков исследования. Я знаю, что оное в моде уже есть. Но почему бы не разнообразить?
С определённого момента игры (ещё early-game) у меня всегда накапливаются тонны опыта (спасибо TiCon + OpenBlocks). И при этом всегда же (на любой сборке, где есть ThaumCraft + аддоны) я (думаю, далеко не один я) испытываю страшнейший дефицит в очках исследования.
Так почему бы не решить обе проблемы (хранение тонн опыта и дефицит очков исследования разом) и не добавить блок/предмет конвертирующий XP в RP?
В целом - это всё. Если идея имеет место в моде, могу поделиться соображениями о том, как я вижу её воплощение.

И ещё. Большое спасибо за ваше творчество.

**Comment by Modbder** [comment]
В моде присудствуют 3 способа генерировать очки исследования(роза мистерия(early game), табак(early game) и разрушитель сущностей(mid/late game)). Зачем ещё больше разнообразия?

![](http://s6.pikabu.ru/images/big_size_comm/2014-09_2/14101605934085.jpeg)

**Comment by Modbder** [comment]
Я не имею ничего против использования куда-то опыта(его действительно слишком много, и делать с ним нечего), но не для RP - способов их генерации уже реально много.
