### ISSUE TITLE
[Bug or Feature] Rosa Mysteria placement

### ISSUE THREAD

**Issue by OneEyeMaker** [Modbder/ThaumicBases#13]
Экспериментируя с Розой Мистерией обнаружил такой баг (хотя, это возможно планировалось как фича) - при попытке посадить семечко на блок, на котором уже растёт цветок, по идее не должно происходить ничего; однако, при этом действии уменьшается размер стака на 1. То есть, можно посадить целый стак (и больше) цветов в одну клетку.
Плюс к тому, при использовании фрагментов в креативе наблюдается странное поведение - вместо того, чтобы выполнить действие без изменения размера стака, стак сначала уменьшается на 1, а потом увеличивается.
Я пока ещё код не глядел, но такое ощущение, что Вы перемудрили с onItemUse и связанными методами.

И да, не знаю насчёт других цветов - есть ли у них эти  баги. Как уже сказал ранее - код пока не смотрел, сказать не могу, где ошибка - в классах Розы Мистерии или в базовых.

**Comment by Modbder** [comment]
Стаксайз уменьшается так:
https://github.com/Modbder/ThaumicBases/blob/master/java/tb/common/item/ItemKnoseFragment.java#L129
Я не перемудрил, а просто не добавил проверку. На мой взгляд она не нужна - в креативе аспекты можно выдать коммандами.
В семечках я просто забыл добавить проверку на блок воздуха. Небольшой баг, но я его поправлю.

**Comment by OneEyeMaker** [comment]
Спасибо за быстрый ответ.
Как добавите проверку на наличие блока - закроете тему.

**Comment by adamsonich** [comment]
//spam
блин, а я выпендривался переводил свои вопросы на английский...

**Comment by Modbder** [comment]
Ну - по хорошему всё же стоит писать на английком по 2-м причинам:

1)Чтобы не путать других людей - они могут захотеть почитать проблемы, и увидят что-то, чего не понимают.
2)Чтобы избежать повторных багрепортов - если человек не понимает, что написано в багрепорте он может зарепортить то же самое ещё раз.
