### ISSUE TITLE
Crash Lava + Pyrofluid

### ISSUE THREAD

**Issue by Danymaddox** [Modbder/ThaumicBases#16]
Hi! firstly I love your mod, is AWESOME! ^^

When you place a bucket of Pyrofluid next to one block of lava the game crash :S

Here you have the crash report ^^

---- Minecraft Crash Report ----

WARNING: coremods are present:
  DCLoadingPlugin (DummyCore-2.1.18.4.jar)
  ThaumcraftLoader (Thaumcraft-1.8-5.0.3.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 24/11/15 19:53
Description: Tesselating block in world

java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=level, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in BlockState{block=thaumicbases:pyrofluid, properties=[metadataOld]}
    at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:165)
    at net.minecraft.client.renderer.BlockFluidRenderer.func_178269_a(SourceFile:240)
    at net.minecraft.client.renderer.BlockFluidRenderer.func_178270_a(SourceFile:64)
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:90)
    at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:178)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
    at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(SourceFile:120)
    at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:882)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1267)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1210)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1035)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:165)
    at net.minecraft.client.renderer.BlockFluidRenderer.func_178269_a(SourceFile:240)
    at net.minecraft.client.renderer.BlockFluidRenderer.func_178270_a(SourceFile:64)

-- Block being tesselated --
Details:
    Block type: ID #10 (tile.lava // net.minecraft.block.BlockDynamicLiquid)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-4,67,249), Chunk: (at 12,4,9 in -1,15; contains blocks -16,0,240 to -1,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:90)
    at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:178)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
    at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(SourceFile:120)
    at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:882)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1267)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1210)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['Danymaddox'/339, l='MpServer', x=-2,60, y=68,00, z=249,07]]
    Chunk stats: MultiplayerChunkCache: 599, 599
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: -8,00,64,00,244,00 - World: (-8,64,244), Chunk: (at 8,4,4 in -1,15; contains blocks -16,0,240 to -1,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 2305 game time, 2305 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 91 total; [EntityAuraNode['Aura Node'/4, l='MpServer', x=-133,50, y=64,50, z=121,50], EntityAuraNode['Aura Node'/5, l='MpServer', x=-137,50, y=63,50, z=340,50], EntitySkeleton['Skeleton'/7191, l='MpServer', x=2,50, y=17,02, z=183,50], EntityZombie['Zombie'/7192, l='MpServer', x=3,50, y=17,02, z=181,50], EntityCreeper['Creeper'/7199, l='MpServer', x=-81,50, y=43,02, z=310,50], EntityItem['item.tile.flower2.poppy'/4128, l='MpServer', x=-18,66, y=63,00, z=298,06], EntitySheep['Sheep'/33, l='MpServer', x=-37,03, y=65,00, z=212,69], EntitySheep['Sheep'/34, l='MpServer', x=-38,53, y=64,00, z=208,50], EntitySheep['Sheep'/35, l='MpServer', x=-32,19, y=64,00, z=205,66], EntitySheep['Sheep'/36, l='MpServer', x=-37,38, y=64,00, z=208,06], EntityHorse['Horse'/37, l='MpServer', x=-42,56, y=64,00, z=208,84], EntityHorse['Horse'/38, l='MpServer', x=-38,06, y=65,00, z=211,19], EntityBat['Bat'/4134, l='MpServer', x=12,39, y=15,40, z=197,25], EntityHorse['Horse'/39, l='MpServer', x=-35,97, y=64,00, z=207,88], EntityHorse['Horse'/40, l='MpServer', x=-42,94, y=67,00, z=218,13], EntityHorse['Horse'/41, l='MpServer', x=-38,13, y=65,00, z=216,28], EntitySheep['Sheep'/42, l='MpServer', x=-28,91, y=65,00, z=217,94], EntitySheep['Sheep'/43, l='MpServer', x=-29,94, y=64,00, z=222,06], EntitySheep['Sheep'/44, l='MpServer', x=-43,31, y=64,00, z=210,31], EntitySheep['Sheep'/45, l='MpServer', x=-31,66, y=64,00, z=219,28], EntityAuraNode['Aura Node'/50, l='MpServer', x=-22,50, y=65,50, z=226,50], EntityAuraNode['Aura Node'/51, l='MpServer', x=-25,50, y=66,50, z=245,50], EntityBat['Bat'/4149, l='MpServer', x=-51,75, y=25,03, z=229,75], EntityBat['Bat'/4150, l='MpServer', x=-40,53, y=39,41, z=219,28], EntityAuraNode['Aura Node'/62, l='MpServer', x=7,50, y=65,50, z=269,50], EntityBat['Bat'/6206, l='MpServer', x=-68,74, y=16,03, z=202,71], EntityBat['Bat'/6207, l='MpServer', x=-73,20, y=19,72, z=222,27], EntityAuraNode['Aura Node'/78, l='MpServer', x=61,50, y=48,50, z=197,50], EntitySheep['Sheep'/79, l='MpServer', x=64,50, y=72,00, z=256,50], EntitySheep['Sheep'/80, l='MpServer', x=65,50, y=72,00, z=253,50], EntitySheep['Sheep'/81, l='MpServer', x=63,78, y=72,00, z=252,78], EntitySheep['Sheep'/82, l='MpServer', x=62,16, y=72,00, z=251,16], EntityAuraNode['Aura Node'/86, l='MpServer', x=116,50, y=63,50, z=363,50], EntityZombie['Zombie'/5207, l='MpServer', x=58,50, y=59,00, z=246,50], EntityAuraNode['Aura Node'/88, l='MpServer', x=128,50, y=64,50, z=219,50], EntitySpider['Spider'/1127, l='MpServer', x=-34,84, y=41,00, z=191,16], EntityCreeper['Creeper'/6323, l='MpServer', x=-22,50, y=30,00, z=225,50], EntitySkeleton['Skeleton'/4315, l='MpServer', x=-49,50, y=33,00, z=215,50], EntityZombie['Zombie'/6380, l='MpServer', x=-23,94, y=46,00, z=234,47], EntityCreeper['Creeper'/6436, l='MpServer', x=71,50, y=29,00, z=285,50], EntitySkeleton['Skeleton'/6437, l='MpServer', x=-16,50, y=46,00, z=213,50], EntitySkeleton['Skeleton'/5438, l='MpServer', x=-9,50, y=29,00, z=173,50], EntityZombie['Zombie'/6498, l='MpServer', x=27,50, y=18,00, z=196,50], EntityBrainyZombie['Angry Zombie'/6499, l='MpServer', x=-16,50, y=20,00, z=210,50], EntitySkeleton['Skeleton'/6500, l='MpServer', x=-21,69, y=18,00, z=205,28], EntityCreeper['Creeper'/5488, l='MpServer', x=-52,50, y=22,00, z=175,50], EntityCreeper['Creeper'/5489, l='MpServer', x=-54,50, y=22,00, z=174,50], EntityItem['item.item.seeds'/4490, l='MpServer', x=-19,44, y=63,00, z=297,91], EntityBat['Bat'/6547, l='MpServer', x=-17,58, y=19,71, z=225,51], EntitySpider['Spider'/4514, l='MpServer', x=-63,88, y=42,09, z=309,69], EntitySkeleton['Skeleton'/6610, l='MpServer', x=-68,50, y=21,00, z=284,50], EntityItem['item.item.seeds'/4601, l='MpServer', x=-11,50, y=64,00, z=283,53], EntityBat['Bat'/6655, l='MpServer', x=-54,69, y=23,34, z=277,03], EntityBat['Bat'/6657, l='MpServer', x=-70,28, y=23,10, z=284,25], EntityZombie['Zombie'/5663, l='MpServer', x=-16,38, y=23,00, z=198,94], EntityZombie['Zombie'/5664, l='MpServer', x=-17,50, y=23,00, z=197,50], EntitySkeleton['Skeleton'/5668, l='MpServer', x=-24,94, y=20,00, z=245,53], EntityItem['item.item.seeds'/3626, l='MpServer', x=29,53, y=63,00, z=294,38], EntitySkeleton['Skeleton'/5674, l='MpServer', x=-11,53, y=12,00, z=177,13], EntityCreeper['Creeper'/4662, l='MpServer', x=-33,31, y=41,00, z=192,97], EntityBat['Bat'/4679, l='MpServer', x=-75,53, y=25,10, z=188,44], EntityBrainyZombie['Angry Zombie'/6728, l='MpServer', x=21,50, y=37,00, z=275,50], EntityZombie['Zombie'/6740, l='MpServer', x=-62,50, y=29,00, z=237,50], EntityZombie['Zombie'/6741, l='MpServer', x=-68,50, y=29,00, z=235,50], EntityZombie['Zombie'/6742, l='MpServer', x=-66,50, y=29,00, z=234,50], EntitySkeleton['Skeleton'/4729, l='MpServer', x=-72,50, y=19,00, z=221,50], EntitySkeleton['Skeleton'/4732, l='MpServer', x=-32,47, y=42,00, z=186,88], EntityCreeper['Creeper'/6782, l='MpServer', x=-72,50, y=42,00, z=310,50], EntityCreeper['Creeper'/6783, l='MpServer', x=-71,50, y=42,00, z=306,50], EntityCreeper['Creeper'/6784, l='MpServer', x=-71,13, y=42,00, z=304,59], EntitySpider['Spider'/6787, l='MpServer', x=-72,90, y=41,69, z=300,11], EntitySpider['Spider'/4779, l='MpServer', x=6,50, y=30,00, z=214,50], EntityItem['item.item.seeds'/3764, l='MpServer', x=32,81, y=63,00, z=292,69], EntityZombie['Zombie'/4806, l='MpServer', x=8,50, y=54,00, z=170,50], EntityCreeper['Creeper'/4807, l='MpServer', x=-3,50, y=13,00, z=199,50], EntityPlayerSP['Danymaddox'/339, l='MpServer', x=-2,60, y=68,00, z=249,07], EntityZombie['Zombie'/4830, l='MpServer', x=73,81, y=28,00, z=299,22], EntityZombie['Zombie'/6939, l='MpServer', x=6,50, y=19,02, z=178,50], EntityItem['item.item.seeds'/3868, l='MpServer', x=34,03, y=63,00, z=294,66], EntityEnderman['Enderman'/5928, l='MpServer', x=-17,78, y=31,00, z=183,50], EntityItem['item.item.seeds'/3893, l='MpServer', x=-51,91, y=69,00, z=245,97], EntitySpider['Spider'/5943, l='MpServer', x=-81,31, y=44,09, z=205,00], EntitySkeleton['Skeleton'/5945, l='MpServer', x=-74,84, y=39,00, z=213,78], EntityCreeper['Creeper'/5947, l='MpServer', x=-70,50, y=39,00, z=214,50], EntityBat['Bat'/5990, l='MpServer', x=-72,97, y=43,81, z=212,76], EntitySkeleton['Skeleton'/4970, l='MpServer', x=-70,50, y=22,02, z=235,50], EntitySkeleton['Skeleton'/4971, l='MpServer', x=-67,72, y=22,02, z=243,25], EntityCreeper['Creeper'/1934, l='MpServer', x=-78,50, y=43,00, z=202,50], EntitySkeleton['Skeleton'/930, l='MpServer', x=-68,78, y=42,00, z=301,22], EntitySkeleton['Skeleton'/7086, l='MpServer', x=-57,50, y=40,02, z=307,50], EntitySkeleton['Skeleton'/6141, l='MpServer', x=-54,50, y=15,00, z=236,50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:351)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2502)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:367)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 649944152 bytes (619 MB) / 1866989568 bytes (1780 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
    IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
    FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1577 7 mods loaded, 7 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.8-11.14.4.1577.jar) 
    UCHIJAAAA   Forge{11.14.4.1577} [Minecraft Forge](forge-1.8-11.14.4.1577.jar) 
    UCHIJAAAA   DummyCore{2.1.18.4.} [DummyCore](DummyCore-2.1.18.4.jar) 
    UCHIJAAAA   Baubles{1.1.1.0} [Baubles](Baubles-1.8-1.1.1.0.jar) 
    UCHIJAAAA   Thaumcraft{5.0.3} [Thaumcraft](Thaumcraft-1.8-5.0.3.jar) 
    UCHIJAAAA   thaumicbases{1.4.18.7} [Thaumic Bases](Thaumic Bases-1.4.18.7.jar) 
    Loaded coremods (and transformers): 
DCLoadingPlugin (DummyCore-2.1.18.4.jar)
  DummyCore.ASM.DCASMManager
ThaumcraftLoader (Thaumcraft-1.8-5.0.3.jar)

```
GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.4.0' Renderer: 'GeForce GTX 750/PCIe/SSE2'
[DummyCore]: 'Special case ASM modification mods: ''Note, that these mods might not be involved in the crash in ANY WAY!''DummyCore just prints some known mods for a lot of ASM modifications''DummyCore'
Launched Version: forge-11.14.4.1577
LWJGL: 2.9.1
OpenGL: GeForce GTX 750/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
```

**Comment by Modbder** [comment]
Fixed
