### ISSUE TITLE
Missing Texture [Maybe dont bug]

### ISSUE THREAD

**Issue by UdoChudo** [Modbder/ThaumicBases#18]
So , i try made modpack for play and i found one problem , all texture from Thaumic Basess missed
Forge version 1568 , 1577 and 1563

**Comment by Modbder** [comment]
Seems like you have a wrong DummyCore version installed. Can I have a look at your game log(fml-client-latest.log)?

**Comment by UdoChudo** [comment]
i used latest version of DummyCore 2.1.8.5
Some ScreenShots and log
http://prntscr.com/98ogai
http://prntscr.com/98ogie
http://prntscr.com/98ogme

[fml-client-latest.txt](https://github.com/Modbder/ThaumicBases/files/47334/fml-client-latest.txt)

**Comment by Modbder** [comment]
Oh, my bad. I forgot to include meta-inf file in the latest release /facepalm
Try to simply download DC 1 version behind, grab the meta-inf folder from that release, put it into your current .jar and see if that works

**Comment by Modbder** [comment]
alernatively try the new build on curse(the one ending with .6) to see if that fixes the issue
