### ISSUE TITLE
[1.7.10] Cannot upgrade Herobrine Scythe's damage

### ISSUE THREAD

**Issue by Mach12** [Modbder/ThaumicBases#22]
The Scycthe of the White-Eyed Omygodthisnameisfartoolong does not seem to respond to Sharpness enchantment, nor to the Wrath (forbidden magic) enchantment.

A Sharpness 5, Wrath 5 Scythe still deals +14.5 damage.

Enchantments work fine, I tested em on a bunch of other modded weapons. Only the scythe does this.

**Comment by Modbder** [comment]
Is the scythe actually dealing that additional damage it is supposed to deal with the corresponding enchantment, or is the damage just fixed to 14,5?

**Comment by Mach12** [comment]
The damage is fixed, it doesn't one shot endermen with full enchantment.

**Comment by Modbder** [comment]
Fixed for the 1.8.9 version
