### ISSUE TITLE
broken(?) adv furnace

### ISSUE THREAD

**Issue by adamsonich** [Modbder/ThaumicBases#23]
I have this https://yadi.sk/d/udF1QN8AmMgCb
tryed with wood logs, crafting tables, alumentium.
rebuild construction on over place.
tryed use thaum pipes with it. 
nothing helped.
version ThaumicBases-1.3.1710.4
Имею очень странный баг с продвинутой печкой.
печь разбивает, но не отдает.

**Comment by Modbder** [comment]
The furnace is removed in 1.4 version.
