### ISSUE TITLE
[1.8.9] Game freeze while loading

### ISSUE THREAD

**Issue by 63502** [Modbder/ThaumicBases#26]
When Dummy Core and Thaumic bases are installed, the game freezes while loading. It also freezes if only dummy core is installed. It does not crash though.

Currently using:

ThaumicBases-2.1.189.9.jar
DummyCore-2.1.189.9.jar

**Comment by Modbder** [comment]
Seems like ASM failure of some sorts. I would need a log to see what is going on though... It is impossible to fix without stacktrace... What forge version are you using?

**Comment by Modbder** [comment]
...caught it. Wait a minute for me to track the error down...

**Comment by Modbder** [comment]
...and it is fixed. Wait for the mod to get updated on the curse and thanks for the bugreport!

**Comment by 63502** [comment]
:D

**Comment by 63502** [comment]
............and now the game will not load at all. It says that it wants version 2.1.189.7 of dummy Core.

**Comment by Modbder** [comment]
Oh, it is not able to figure out a version correctly... Wait some more time for curse to update the file on their website.

**Comment by Modbder** [comment]
supposed to be working now(2 == 2, 1 == 1, 189 > 188, 12 > 7)

**Comment by 63502** [comment]
...AAAAAAND (wait for it)......

......now it works perfectly. :D

**Comment by 63502** [comment]
GG
