### ISSUE TITLE
Chiseled stone brick + Ordo = Chiseled stone brick in Crucible

### ISSUE THREAD

**Issue by Imnuts7** [Modbder/ThaumicBases#28]
This is really annoying if you want to make thaumium because this recipe comes first

**Comment by darwithe** [comment]
Considering the fact that chiseled stone brick now has a vanilla crafting recipe I'd honestly suggest just yanking the chiseled stone brick recipe completely.

**Comment by Modbder** [comment]
Removed that recipe, as you've suggested, since there is already a recipe for that.
