### ISSUE TITLE
[1.8.9] Dupe bug with bloody enchanted fabric

### ISSUE THREAD

**Issue by Kazzamkablam** [Modbder/ThaumicBases#29]
You can craft items using it without crafting table consuming materials. 

Update: Seems to dupe other items from the mod too...

**Comment by Modbder** [comment]
Seems to be an issue in TC itself, since there is no control over that sort of things in the recipe registration, and the only way items can stay in the crafting grid is if they have a containerItem, which is null for TB's materials

**Comment by Modbder** [comment]
Oh, finally found a case for the issue. Fixed.
