### ISSUE TITLE
Crash while infusing the primal bracelet

### ISSUE THREAD

**Issue by jrpoints** [Modbder/ThaumicBases#32]
I was playing on my server where I was making the primal bracelet and at the end of the ascentia  infusion part whiles infusing the 96 potentia, I got this crash but client side only. When I tried to log back in I crashed again but could hear the infusion process still going, area isn't chunk loaded so progress stopped when I crashed. Couple more restarts and I was able to load in long enough for it to finish and all seems to have gone back to normal. Not sure what to make of it.

[http://pastebin.com/Ge5KXmYg](url)

**Comment by Modbder** [comment]
That is a DC related issue, not TB one. Meh, in the end I'll just copy Reika's idea of keeping all issues in 1 git project... Anyway, I will fix that asap

**Comment by Modbder** [comment]
Fixed.
