### ISSUE TITLE
Primal enchant and efficiency not compatible on revolver. 

### ISSUE THREAD

**Issue by jrpoints** [Modbder/ThaumicBases#35]
I added efficiency up to 5 on my thaumaturges revolver and was getting 7 shots per point of essentia, I then added primal to it, because in the book it said it didn't conflict, thinking I would maybe get 3-4 shots per point or whatever but it overwrote the efficiency and I was only getting 1 shot per 2 essentia. I tested if maybe the order that it applies mattered so I did primal first then efficiency but that didnt matter.

So either the book is wrong and it does conflict and overwrite efficiency and needs to be changed or the primal enchant need to be fixed to work with efficiency.

**Comment by Modbder** [comment]
Fixed
