### ISSUE TITLE
Enchantment ID conflict with EvilCraft

### ISSUE THREAD

**Issue by LlubNek** [Modbder/ThaumicBases#37]
You have an enchantment ID conflict with EvilCraft (enchantment ID 101).

Here's the crash report:
http://pastebin.com/YHTkDP8S

Here's the log:
http://pastebin.com/2rkPtfbE

Here's a link to the matching issue for EvilCraft:
https://github.com/CyclopsMC/EvilCraft/issues/335

**Comment by Modbder** [comment]
There is a .cfg file for that
