### ISSUE TITLE
[1.8.9 Bug] Using trusty magical ukulele crash

### ISSUE THREAD

**Issue by SunnyTD** [Modbder/ThaumicBases#43]
Specifically, the ukulele that adds warp ward and such. I also tried the knowledge ukulele, and that crashed the game as well. Logs for the warp ward ukulele crash are below.

MC log: https://gist.github.com/SunnyTD/a79cb540448d580336a0
FML log: https://gist.github.com/SunnyTD/fd75abf6b9d5503bcdfb

**Comment by Modbder** [comment]
Oh no, Azanor changed his API again...

**Comment by LiSirNo** [comment]
Not sure if this will help but there is crash log when using bard one

https://gist.github.com/LiSirNo/52b2727eeea383cf1f4d
