### ISSUE TITLE
[1.8.9] Wands made from Thaumite Rod use old TC4 vis costs

### ISSUE THREAD

**Issue by codewarrior0** [Modbder/ThaumicBases#48]
ThaumicBases-2.1.189.32

Crafting a wand with a Thaumite Rod as the core costs much less vis than any of the TC5 wand cores. It looks like the vis costs weren't updated to match TC5 vis costs.

**Comment by Modbder** [comment]
I have changed that in the latest version, I believe

**Comment by codewarrior0** [comment]
Ah, the vis _capacity_ of the wand cores was updated, but the _crafting cost_ was not. A wand with thauminite caps and core costs 216 vis to craft; a standard Thaumium Capped Silverwood wand costs 324.

**Comment by codewarrior0** [comment]
Never mind. Thaumcraft itself scaled up the crafting cost of the wand cores for you. I thought it hadn't been updated because of how cheap the thaumium core is to craft with. (The crafting cost is like greatwood, but the capacity is closer to silverwood...).
