### ISSUE TITLE
Entity FX crash

### ISSUE THREAD

**Issue by NullMagic** [Modbder/ThaumicBases#5]
Alright, we're getting a crash at server start (but not client side) that causes a crash, at first we thought it was another mod we were having trouble with, but after removing that mod the error happened again and we tracked it down to the latest version of Thaumic Bases (Because I clearly can't read error reports worth a damn. Don't judge me >.>)

Crash Report: http://pastebin.com/cnQhH6z7

**Comment by Modbder** [comment]
Already fixed in 34ce428fee67c9f837968c850d922b6a6b91ec2d
Untill the version is released use the server-side fix in the Releases section here, on github.

**Comment by NullMagic** [comment]
Awesome, thanks for the quick response!
