### ISSUE TITLE
Client crashes when scanning the experience focus

### ISSUE THREAD

**Issue by BeardStroker** [Modbder/ThaumicBases#7]
http://pastebin.com/YMy1BYgC

Tried several times, same crash :) Also it seems like even though the focus says it should only use ordo and perdito, it actually uses every primal aspect from the staff. And lastly you can use the focus on grass for no cost at all and still get xp :P Love your work on the mod so far, I hope you keep it up :)

**Comment by Modbder** [comment]
Not a TB issue - some mod creates a recursion at TC's aspect registry. This has already been reported to Azanor a several times. I guess I will make a patch so TB will not trigger that, but just so you know - not a problem of the actual mod.
